added _classes for knn classifiers
mljar/mljar-supervised pull request #679
Opened 2023-11-30 11:57 UTC by Hk669

### **Added _classes attribute for k-Nearest Neighbors (KNN) Algorithm**

**Description:**
This pull request addresses the issue [#669 ](https://github.com/mljar/mljar-supervised/issues/669) and implements the addition of the _classes attribute for the k-Nearest Neighbors algorithm.

**Changes Made:**

Modified the KNNFit class to include the _classes attribute, providing unique classes based on the fitted model.
Updated the KNeighborsAlgorithm and KNeighborsRegressorAlgorithm classes to inherit from KNNFit and ClassifierMixin and RegressorMixin, respectively.
Adjusted relevant unit tests to ensure the proper functioning of the _classes attribute.

**Testing:**

- [x] Unit tests (test_knn.py) have been added/modified to check the functionality of the _classes attribute.
- [x] All tests pass successfully.

## checklist:
 - [x] Added _classes attribute.
 - [x] Updated unit tests.
 - [x] Checked compatibility and consistency.
<img width="938" alt="tests_knn1" src="https://github.com/mljar/mljar-supervised/assets/96101829/af6a9b47-8d32-409b-968b-eb43dd8d875a">
<img width="947" alt="tests_knn" src="https://github.com/mljar/mljar-supervised/assets/96101829/a2a8f92c-d626-471a-8b25-a76c6989f8d0">
<img width="943" alt="classes_property" src="https://github.com/mljar/mljar-supervised/assets/96101829/5bc48649-231d-456c-b593-fcbc4ad50d21">

2023-12-01 11:22 UTC, pplonski requested changes
Thank you for PR. Please check how classes are derived, because now we get some strange nesting between base classes.

2023-12-01 11:22 UTC, pplonski commented on supervised/algorithms/knn.py
> +class KNeighborsAlgorithm(KNNFit, ClassifierMixin):
this looks strange, we derive from `ClassifierMixin` in KNNFit as well ...

2023-12-01 11:22 UTC, pplonski commented on supervised/algorithms/knn.py
> +class KNeighborsRegressorAlgorithm(KNNFit, RegressorMixin):
we derive from `KNNFit` which derives from `ClassifierMixin` and we also derive from `RegressorMixin`. This looks strange ...

2023-12-01 11:22 UTC, pplonski commented on tests/tests_algorithms/test_knn.py
> +        print("np.unique(self.y):", np.unique(self.y))
we dont need debug statements, let use asserts

2023-12-01 14:47 UTC, Hk669 commented
made the required changes, and its working quite great. 
passed all the unitttests.
<img width="945" alt="tests_knn_new" src="https://github.com/mljar/mljar-supervised/assets/96101829/9e9ee027-d94c-4a45-a98a-74c89dc71b2d">

2023-12-14 13:29 UTC, pplonski approved these changes

2023-12-14 13:29 UTC, merged

2023-12-14 13:30 UTC, pplonski commented
Thank you @Hk669 for PR, good job :1st_place_medal:

2023-12-15 16:33 UTC, Hk669 commented
Thanks for the support @pplonski